version: "3"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/code
      - bundler-volume:/usr/local/bundle
    links:
      - redis
      - postgres
    working_dir: /code
    command: bin/rails s
    environment:
      - REDIS_URL=redis://redis
      - GLOWFIC_DATABASE_HOST=postgres
      - GLOWFIC_DATABASE_USER=postgres
      - GLOWFIC_DATABASE_PASS=postgres
  redis:
    image: redis:3.2-alpine
  postgres:
    environment:
      - POSTGRES_PASSWORD=postgres
    image: postgres:9.4-alpine
    volumes:
      - "./db/storage/:/var/lib/postgresql/data"
  wraith:
    image: bbcnews/wraith
    working_dir: /wraithy
    volumes:
      - "./wraith/:/wraithy"
    depends_on:
      - web

volumes:
  bundler-volume:
