imports: "core.yaml"

# The directory that your base screenshots will be stored in.
history_dir: 'then/default'

# The directory that your latest screenshots will be stored in
directory: 'now/default'
